// Phase 5 — System Integration & Deployment (RFL Academy template)
const fs = require("fs");
const { Packer } = require("docx");
const T = require("../_assets/rfl_template.js");
const { SEC, SUBSEC, P, bullet, callout, code, dataTable, imgPlaceholder, titleBlock, spacer, buildDoc, CONTENT_W } = T;

const children = [
  ...titleBlock("System Integration & Deployment", "Multi-Factor Driver Authentication System  ·  Phase 5"),

  SEC("Overview", 1),
  P("Phase 5 is the integration and deployment phase. It ties together every subsystem built in Phases 1–4 — face recognition, fingerprint, relay/ignition, and GSM/SMS — into a single always-on application driven by a state machine and presented as a full-screen kiosk. Main.py is the orchestrator: it owns the camera, the UI, the state transitions, and the routing of SMS commands to every other module."),
  SUBSEC("1.1 Project Context"),
  P("The earlier phases each delivered a working subsystem in isolation. In a vehicle, those subsystems must run together, unattended, and recover on their own — booting straight into a display-only kiosk, authenticating drivers, actuating the ignition, and staying reachable by SMS, all with no keyboard attached. Phase 5 is what makes that happen."),
  SUBSEC("1.2 Key Integration Points"),
  bullet("A central state machine coordinating idle, registration, authentication, sleep, first-boot, and reset"),
  bullet("A single full-screen OpenCV window rendering camera, status, and SMS command panels"),
  bullet("Picamera2 capture feeding both live preview and the recognition workers"),
  bullet("A guided first-boot setup wizard driven entirely over SMS"),
  bullet("A threading model that keeps the UI smooth while workers and the GSM poller run in the background"),
  bullet("Power-aware lifecycle: timer-latch hold on boot, safe relay release on shutdown"),
  spacer(),
  callout("Phase Scope", "Phase 5 documents how the modules from Phases 1–4 are assembled in Main.py — the state machine, main loop, UI, lifecycle, and deployment. The internal behaviour of each subsystem is covered in its own phase document."),

  SEC("Integrated Architecture", 2),
  SUBSEC("2.1 Module Map"),
  P("Main.py imports each subsystem as a module and coordinates them. No subsystem talks to another directly — Main.py is the single point of integration."),
  dataTable(["Module", "Role in the System", "Phase"], [
    ["FaceDetection (fd)", "Haar detection, LBPH recognition, brightness", "1"],
    ["fingerprint_sim (fp)", "R307S enrollment and verification", "2"],
    ["relay_controller (relay)", "Timer latch, LED, ignition relays", "3"],
    ["sms_alert (sms)", "GSM send + GsmPoller command receive", "4"],
    ["logger (lg)", "Event + session CSV logs, USB export", "1–5"],
    ["first_boot (fb)", "First-run setup wizard state", "5"],
    ["Main.py", "State machine, UI, lifecycle, SMS dispatch", "5"],
  ], [2500, CONTENT_W - 4100, 1600]),
  spacer(),
  SUBSEC("2.2 Threading Model"),
  P("The main thread runs the render loop, the state machine, and all SMS command handling — so all shared-state mutation happens in one place, with no locks needed around it. Long-running jobs run on background threads and report back via small shared state objects:"),
  bullet("Main thread — camera read, UI render, state transitions, SMS dispatch"),
  bullet("Worker threads — face registration, fingerprint enrollment, and authentication"),
  bullet("GsmPoller thread — continuous inbound SMS polling (Phase 4)"),
  bullet("Send threads — each outbound SMS on its own short-lived connection"),

  SEC("State Machine", 3),
  P("The system is always in exactly one state. SMS commands and sensor events drive the transitions."),
  dataTable(["State", "Meaning"], [
    ["IDLE", "Live preview; watching for a face and listening for SMS"],
    ["FIRST_BOOT", "Guided setup wizard (password → face → fingerprint → phone)"],
    ["REG_FACE / REG_FP", "Face registration / fingerprint enrollment in progress"],
    ["AUTHING", "Authentication running (manual or automatic)"],
    ["RESULT", "Showing the GRANTED / DENIED outcome"],
    ["RESETTING", "Data reset being executed"],
    ["SLEEPING", "Display dimmed after inactivity; SMS still active"],
  ], [2400, CONTENT_W - 2400]),
  imgPlaceholder("State Machine Diagram"),

  SEC("Main Loop & First-Boot", 4),
  SUBSEC("4.1 Per-Frame Pipeline"),
  bullet("Capture a frame from Picamera2 and mirror it; measure brightness and run LED auto-control"),
  bullet("Run lightweight idle face detection; manage sleep; trigger first-detection / periodic auto-auth"),
  bullet("Advance the first-boot wizard, registration, and authentication completion handlers"),
  bullet("Drain the SMS command queue and dispatch each command; render the kiosk canvas"),
  spacer(),
  callout("Auto-Authentication", "While IDLE, the system periodically runs a passive face-only check (every AUTO_AUTH_INTERVAL seconds) and also authenticates the first time a face appears. A failed auto-check raises an on-screen “UNAUTHORISED INDIVIDUAL DETECTED” alert and forces the ignition off; it never enables ignition on its own."),
  spacer(),
  SUBSEC("4.2 First-Boot Setup Wizard"),
  P("On the very first run, first_boot.py tracks setup completion in setup_complete.json and the wizard walks the owner through configuration — entirely over SMS, since the kiosk has no keyboard."),
  dataTable(["Step", "Required?", "Completed By"], [
    ["password", "Required", "SET PASSWORD <pwd>"],
    ["face", "Required", "REGISTER FACE"],
    ["fingerprint", "Required", "REGISTER FP"],
    ["phone", "Optional (prompted)", "REGISTER PHONE <num>"],
  ], [2400, 2400, CONTENT_W - 4800]),
  P("Each completed step is timestamped. Once the required steps are done, setup is marked complete and the system drops into normal IDLE operation. A full data reset clears the flag so the wizard runs again on next boot."),

  SEC("Kiosk UI, Sleep & Security", 5),
  SUBSEC("5.1 Kiosk UI"),
  P("The entire UI is one OpenCV window opened in full-screen mode, display-only — all control is by SMS. A composed canvas is redrawn each frame from a camera pane and an information sidebar (Face / Fingerprint / Phone readiness, LED state and measured brightness, an SMS command panel, and overlays for registration guidance, the authentication result, the IGNITION ON banner, and a reset-pending notice). At startup the app auto-detects the GTK / Wayland / X11 backend so the same code runs under the Pi's Wayland/labwc session and on desktops."),
  SUBSEC("5.2 Sleep & Wake"),
  P("After the idle timeout the display enters a low-activity SLEEPING state; a shorter timeout is used after an authentication. SMS commands remain fully active while sleeping, and the system wakes on either an incoming command or a detected face."),
  SUBSEC("5.3 Data Reset & Security"),
  P("Reset is two-step and password-protected: RESET puts the system into a pending state and replies with the confirmation format; RESET CONFIRM <pwd> then erases the face model, fingerprint enrollment, and saved phone, and clears the setup flag so the first-boot wizard runs again."),
  callout("Admin Password", "The admin password (default 1234, stored in admin_password.txt) guards destructive actions. SET PASSWORD changes it; RESET CONFIRM requires it. Change it from the default during first-boot setup.", "C0392B", "FCEDEC"),

  SEC("Lifecycle, Config & Deployment", 6),
  SUBSEC("6.1 Startup & Shutdown"),
  bullet("Configure the display backend and import all subsystem modules"),
  bullet("relay_init() — initialise GPIO and energise the timer latch (hold power on)"),
  bullet("Initialise logs; load the saved password, face model, and enrollment flags"),
  bullet("Start the Picamera2 capture and the GSM command poller"),
  bullet("Open the full-screen window; enter FIRST_BOOT if setup is incomplete, else IDLE"),
  bullet("On exit, relay_shutdown() releases ignition + LED but leaves the timer latch ON (never cleanup())"),
  spacer(),
  callout("Power-Safe Lifecycle", "The timer latch is energised first on boot and left on through shutdown. With the external boot timer, this guarantees the Pi has stable power for its entire run and is never dropped mid-operation by the relay logic.", T.GREEN, "EAF7EF"),
  spacer(),
  SUBSEC("6.2 Key Configuration"),
  dataTable(["Constant", "Value", "Description"], [
    ["TARGET_FPS", "15", "UI render / loop frame rate"],
    ["AUTO_AUTH_INTERVAL", "300", "Seconds between passive auto-auth checks"],
    ["SLEEP_TIMEOUT / POST_AUTH", "120 / 30", "Idle seconds before SLEEPING"],
    ["DEFAULT_PASSWORD", "1234", "Initial admin password (change on first boot)"],
  ], [3200, 1700, CONTENT_W - 4900]),
  spacer(),
  SUBSEC("6.3 Deployment & Autostart"),
  code([
    "pip install opencv-contrib-python numpy picamera2 \\",
    "            pyfingerprint pyserial RPi.GPIO --break-system-packages",
    "python3 Main.py",
  ]),
  P("The in-app full-screen kiosk is implemented; the OS-level autostart entry that launches Main.py at session start (Wayland/labwc) is the final commissioning step and should be added during deployment."),
  spacer(),
  SUBSEC("6.4 Known Limitations & Conclusion"),
  bullet("Single-driver only — one face profile and one fingerprint are supported across the system."),
  bullet("OS-level autostart/kiosk service is a pending commissioning step, not yet committed to the repo."),
  bullet("The GSM link is the main open hardware dependency; without it, remote control and alerts are unavailable (Phase 4)."),
  spacer(),
  P("With Phase 5 the Multi-Factor Driver Authentication System is functionally complete: a single Raspberry Pi application that recognises a driver's face and fingerprint, gates the vehicle's ignition through a relay, keeps itself powered through a timer latch, and is fully operable and observable by SMS — presented as an unattended full-screen kiosk. The five phases together document the system end to end."),
];

const doc = buildDoc({ runningTitle: "Multi-Factor Driver Authentication System  |  Phase 5 Documentation", children });
Packer.toBuffer(doc).then(buf => { fs.writeFileSync(__dirname + "/Phase5_Documentation.docx", buf); console.log("WROTE Phase5 (" + buf.length + " bytes)"); });
